### ISSUE TITLE
[BUG] Realestate wont create houses

### ISSUE THREAD

**Issue by Surrealsounds** [Qbox-project/qb-houses#1]
**Describe the bug**
When i set my job to real estate i cant create houses with the command /createhouse
**To Reproduce**
1:use the command "/setjob realestate"
2:use the command "/createhouse 1 1"
**Expected behavior**
I expected the house to create so that i could furnish it

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Yesterday
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] "Ploks Civillian Car pack"
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**

**Comment by YvanCywan** [comment]
I've just tested the addon and it seems to be working just fine, would you be able to provide any more information, such as F8 errors, etc?

**Comment by maejok-xx** [comment]
you're not using the command correctly
it's `/setjob <PlayerId> <Job>`

**Comment by YvanCywan** [comment]
Closing since this has long been resolved.
